chromium/badssl.com

- domains/self-signed.badssl.com/test/imported.js
This adds a test JavaScript file on the self-signed.badssl.com subdomain that can be used for testing the interaction with other secure or insecure pages.
> Added JavaScript file for including in tests

- domains/misc/mixed.badssl.com/index.html
- domains/misc/very.badssl.com/index.html
To fix the issue at https://code.google.com/p/chromium/issues/detail?id=499426
Are the alt-texts good enough? Thanks.
> Improve screen reader support

- Makefile
Just generally makes cleaning up after myself a heck of a lot easier.
P.S.: Please don't run this by accident on the production server.
> Add a 'make clean' option

- Makefile
- README.md
> Added "make docker" command.

- Dockerfile
- Makefile
- _config.yml
Jekyll should build properly and all the certs should now install correctly.
> Fix the dockerfile

- Dockerfile
This updates us to Ubuntu 16.04.
> Update docker to 16.04

- common/test/theme-color/index.html
@marumari Does this look okay to you?
We need it for some Chrome test plans.
> Add theme color test.

- domains/misc/badssl.com/index.html
> Add `revoked` to the front page. Closes #210.

- Dockerfile
Ubuntu docker version in comment is now corrected to 16.04
> Fix docker ubuntu version comment

- domains/misc/badssl.com/funky/funky.css
- domains/misc/badssl.com/funky/funky.js
- domains/misc/badssl.com/index.html
> Mark SHA-1 subdomains as retired; move HTTP input below mixed content for column for balance.

- domains/misc/badssl.com/front-page-icons/external-white.svg
- domains/misc/badssl.com/front-page-icons/external.svg
- domains/misc/badssl.com/index.css
- domains/misc/badssl.com/index.html
> Add a link to Safe Browsing tests from the front page.

- certs/src/conf/subdomain-ecc256.conf
- certs/src/conf/subdomain-ecc384.conf
> Updated ECC Subdomains to Wildcard

- common/input/dynamic-login/index.html
- common/input/login/index.html
- domains/input/http-dynamic-login/index.html
- domains/input/http-login/index.html
Adds the autocomplete=username attribute to the login fields so autofill "Form Not Secure" recognizes these fields before the user has stored a credential.
> Add autocomplete=username attribute to login forms

- domains/misc/badssl.com/index.html
- domains/mixed/mixed-form.conf
- domains/mixed/mixed-form/index.html
I'm doing some work to clean up our handling of "mixed" pages where the mixed content is a form that targets HTTP. PTAL?
> Add a form that submits non-securely

- domains/mixed/very/index.html
Update very mixed HTTPS page with non-secure file download and non-secure form.
> Add more mixed content to very.badssl.com

- common/input/web-payment/index.js
> Exercise PaymentRequest.canMakePayment() API.

- domains/misc/badssl.com/dashboard/sets.js
> add missing domain incomplete-chain

- README.md
Using the UI is for chumps and also way more steps.
> Update macOS install instructions

- nginx-includes/tls-defaults.conf
> Default 2048 bit DH (fix #302)

- domains/protocol/tls-v1-2.conf
Tahnks to @ExE-Boss for noticing.
> Fix redirect port for `tls-v1-2`.

- domains/key-exchange/dh1024/index.html
- domains/key-exchange/dh2048/index.html
- domains/key-exchange/dh480/index.html
- domains/key-exchange/dh512/index.html
@christhompson, could you review?
I know it's holiday season/end of year, so absolutely no rush. :-)
> Remove hyphens from dh domain pages. Fixes #379

- domains/misc/badssl.com/index.html
Site was shut down.
Fixes issue #452.
> Remove link to mitm.watch (site shut down)
