chromium/badssl.com

certs/cert-generator/cert-generator.sh
If you run cert-generator alone, it will prompt you to regenerate the root keys/certs as well as the DH parameters.  You can also just run it as $ cert-generator.sh y, in which case it will regenerate them without asking, to be used when the Makefile is rewritten.
=> Change cert generator to prompt you to regenerate certs/keys

common/common.conf, common/password/index.html, domains/misc/badssl.com/index.html
Should be visible at: http://http.badssl.com/password/
Screenshot: http://i.imgur.com/PGUrh1W.png
As per this upcoming Firefox change: https://twitter.com/rlbarnes/status/656554266744586240
P.S.: The public site has been very very slow lately
P.P.S.: Styling placeholder text is the literal worst
=> Add http password site

domains/misc/https-everywhere.badssl.com-http/index.html, domains/misc/https-everywhere.badssl.com-http/redirect-test/status.svg, domains/misc/https-everywhere.badssl.com-https/index.html, domains/misc/https-everywhere.badssl.com-https/redirect-test/status.svg, domains/misc/https-everywhere.badssl.com.conf
I tried my luck to close https://github.com/lgarron/badssl.com/issues/80
Please test it and also note that https://github.com/EFForg/https-everywhere/pull/3111 has to be merged first and a HTTPS-E version including the new ruleset has to be published to make this work.
After this has been done we should replace  the `[unknown]` placeholder with the version of HTTPS-E released.
=> New domain: https-everywhere

Makefile, _config.yml, certs/cert-generator/cert-self-signed-symlink-generator.sh
- Instead of copying all the certs from certs into common/certs, it just creates a symlink
- If a file doesn't exist in the certs directory (but it does in self-signed), it will create a symlink into self-signed
- Jekyll no longer blows away the created keys
Should fix #133 hopefully!
=> Hopefully fix all the jekyll issues

certs/cert-generator/badssl-fallback.conf, certs/cert-generator/cert-generator.sh, domains/misc/badssl.com.conf, domains/misc/www.badssl.com.conf, fallback.conf, nginx-includes/wildcard.fallback.conf, nginx.conf
@marumari, could you review this band-aid?
=> Use a fallback certificate for port 443 to avoid SNI connection false positives. Addresses #146.

domains/cert/preloaded-expect-ct.conf, domains/cert/preloaded-expect-ct/index.html, nginx-includes/wildcard.preloaded-expect-ct.conf
This subdomain serves the Expect-CT header and is on the Chrome preload
list for Expect-CT, but does not serve SCTs. Visiting it in Chrome
should thus generate and send an Expect-CT report.
=> Add preloaded-expect-ct.badssl.com

common/input/dynamic-login/index.html, common/input/login/index.html, domains/input/http-credit-card.conf, domains/input/http-credit-card/index.html, domains/input/http-dynamic-login.conf, domains/input/http-dynamic-login/index.html, domains/input/http-login.conf, domains/input/http-login/index.html, domains/input/http-password.conf, domains/input/http-password/index.html, domains/misc/badssl.com/index.html
@marumari, could you review these changes?
They're for testing the Chrome changes in https://blog.chromium.org/2016/12/chrome-56-beta-not-secure-warning-web.html
After this change:
- `http-login.badssl.com`
- `http-dynamic-login.badssl.com`
- `http-credit-card.badssl.com`
- `http-password.badssl.com` (already existed)
as well as `common` tests on each domain at:
- `input/login`
- `input/dynamic-login`
- `input/credit-card` (already existed)
- `input/password` (already existed)
The regular password case now also includes a plain password field without a form, since that can affects behaviour on iOS that we care about.
=> Add login and dynamic-login pages and subdomains.

certs/Makefile, certs/src/conf/subdomain-ecc256.conf, certs/src/conf/subdomain-ecc384.conf, certs/tool, domains-local-only/cert/ecc256.conf, domains-local-only/cert/ecc256/index.html, domains-local-only/cert/ecc384.conf, domains-local-only/cert/ecc384/index.html, nginx-includes/subdomain-ecc256.conf, nginx-includes/subdomain-ecc384.conf
The code has been tested in a Google Compute Engine VM running Debian GNU/Linux 8 (jessie). 
The installation was simple and it was running in minutes using the instructions provided on the main page.
Note: I edited the Makefile locally on the VM to include the domain name for testing purposes.
=> Added ECC 256 and 384 to BadSSL (Local Only)

domains/misc/badssl.com/dashboard/sets.js, domains/misc/badssl.com/index.html, domains/misc/badssl.com/index.js
This PR adds TLS1.0, TLS1.1, SSLv2 and SSLv3 to the front page under the client section. Also the Dashboard now checks SSLv3 and SSLv2
=> add protocols to main page

Dockerfile
For some reason `ruby gem` fails with the current version of Ubuntu. Adding libffi-dev to the required libraries seems to have fixed it.
=> Add libffi-dev to the required packages in Docker

_plugins/environment_variable.rb, certs/Makefile, certs/src/conf/subdomain-extended-validation.conf, domains/cert/extended-validation.conf, domains/cert/extended-validation/index.html, domains/misc/badssl.com/dashboard/sets.js, domains/misc/badssl.com/index.html, nginx-includes/subdomain-extended-validation.conf
Here's the first go at it. It's a bit awkward, so feel free to let me know what you truly think.  :)
=> Add support for an extended validation certificate

domains/misc/badssl.com/dashboard/sets.js, domains/misc/badssl.com/index.html, domains/protocol/tls-v1-2.conf, domains/protocol/tls-v1-2/index.html, nginx-includes/tls-v1-2.conf
@christhompson, could you review?
This adds `tls-v1-2` on port 1012, similar to how other protocol subdomains are implemented.
=> Add `tls-v1-2` subdomain. Addresses #332.

Makefile
The current `make link` target checks if `/etc/nginx/nginx.conf` exists, and if it doesn't then it adds the virtual host include for the badssl config. However, it `make link` is run more than once (such as during a re-install on a previously deployed server), this can cause the line to be added more than once (and then causing the nginx config to fail).
This changes it to explicitly test if the line exists in the file, and if it does not then it adds it to the next line.
It also separates out the file existence check and warning.
=> Change 'make link' to be idempotent

domains/misc/badssl.com/dashboard/index.css, domains/misc/badssl.com/dashboard/index.js, domains/misc/badssl.com/dashboard/sets.js
This also reorganizes the sections a bit. In particular, the top sections are split up by the risk that a failure indicates.
=> Add descriptions to the dashboard sections.

domains/misc/badssl.com/download/index.html
Completely overlooked it just like in #369, hopefully this overkill formatting tweak can help those later.
=> Tweak formatting for client cert passwords

common/input/web-payment/index.html, common/input/web-payment/index.js, common/style.css
For easier debugging on mobile devices, print the API return values and
exception messages in the footer area of the page.
=> Print API return values and exceptions in the footer.

certs/Makefile
Presently, the untrusted root test is indistinguishable from an
incomplete certificate chain. As a consequence, client libraries
may reject such a certificate as an incomplete chain, but would
otherwise accept the chain if there was a leaf/end-entity
certificate signed by a self-signed certificate.
Fixes https://github.com/chromium/badssl.com/issues/396
=> Explicitly send the self-signed root for untrusted-root

Dockerfile, _layouts/page.html, domains/misc/badssl.com/index.html, domains/ui/lock-title.conf, domains/ui/lock-title/index.html
This adds `lock-title.badssl.com` (available over both http:// and https://), which sets the page title to "🔒 lock-title".
Fixes #329
=> Add page with 🔒 in title

domains/key-exchange/dh1024/index.html, domains/key-exchange/dh2048/index.html, domains/misc/badssl.com/dashboard/sets.js, domains/misc/badssl.com/index.html
This updates the icons/labels for dh1024 and dh2048 from "dubious" and "good" to "bad" and "dubious", and adds dh2048 to the "Legacy Cryptography" section of the Dashboard.
It is now over two years since non-EC DHE support was removed from Chrome (https://www.chromestatus.com/feature/5128908798164992) after the Logjam attacks indicated that DHE key exchange was generally insecure. While 2048-bit DH is still ~okay (that's large enough that we don't think it's currently breakable, but attacks only get better), I think it makes sense to mark it as "dubious" and add it to the "Legacy Cryptography" section of the dashboard. Modern configurations should strongly favor ECDHE.
1024-bit DH was already added to the Dashboard view under "Broken Cryptography", so actively labeling it as "bad" on the …
=> Mark DHE as bad or dubious

certs/Makefile, certs/src/conf/subdomain-blocked-interception.conf, certs/src/conf/subdomain-known-interception.conf, domains/cert/blocked-interception.conf, domains/cert/blocked-interception/index.html, domains/cert/known-interception.conf, domains/cert/known-interception/index.html, nginx-includes/subdomain-blocked-interception.conf, nginx-includes/subdomain-known-interception.conf
In Chrome, we are adding two new variations of CRLSets for when we want to block or alert on certificates or roots that are known to be used for network interception and monitoring (the new CRLSet types and errors were added in https://crrev.com/c/1904545).
To help with manual testing, this PR adds two new subdomains that will serve new (trusted) certificates with new keys for each:
- blocked-interception.badssl.com (Chrome would show a new interstitial)
- known-interception.badssl.com (Chrome would show a new passive warning)
After these certificates are issued, my plan is to add them to the new CRLSets lists (in Chrome source and in the component). Non-Chrome browsers won't pick up these new CRLSets by default.
I wanted to file the initial version of this PR to solicit reviews from …
=> Add (known|blocked)-interception.badssl.com tests

domains/misc/badssl.com/dashboard/sets.js, domains/misc/badssl.com/index.html
`invalid-expected-sct` has expired with no way to renew it (replaced by `no-sct`). Similarly, `sha1-intermediate` will expire on May 30, 2020, and CAs can no longer issue new ones using SHA-1. This moves both to the "Defunct" section of the homepage and removes them from the dashboard.
Fixes #416
=> Mark invalid-expected-sct and sha1-intermediate as Defunct

domains/misc/badssl.com/dashboard/sets.js, domains/misc/badssl.com/index.html
This is (unfortunately) currently broken due to nginx not allowing us to intentionally serve a chain out-of-order (see https://github.com/chromium/badssl.com/pull/443#issuecomment-784556007 for details). For now, remove this test case from the dashboard and homepage lists until we can figure out a solution.
=> Remove reversed-chain from homepage/dashboard

common/input/web-payment/index.js
The basic-card feature is being deprecated, so this test page is updated to use a test payment app instead.
=> Use bobbucks instead of basic-card on web-payment page.
